server.port: 7003
server.error.include-message: always

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

logging: 
  level: 
    root: INFO
    dev.agasen: DEBUG
    se.magnus: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/review-db
  username: user
  password: pwd