server.port: 7003
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
# this is to satisfy Docker testing
# TODO: Create a volume for Table DDL
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

logging: 
  level: 
    root: INFO
    dev.agasen: DEBUG
    se.magnus: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/review-db
  username: user
  password: pwd